"""Generate CEO daily PDF report (ReportLab)."""

from __future__ import annotations

from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.services.dashboard_service import get_ceo_dashboard


def build_daily_pdf_bytes() -> bytes:
    """Requires Flask application context for DB access."""
    data = get_ceo_dashboard()
    ex = data.get("executive") or {}
    kpi = ex.get("overall_kpi") or {}
    fin = ex.get("financial_exposure") or {}
    comp = ex.get("compliance") or {}
    alerts = ex.get("insider_alerts") or []
    assets = ex.get("top_risky_assets") or []

    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter, title="LockNLog CEO Daily Report")
    styles = getSampleStyleSheet()
    story: list = []

    story.append(Paragraph("LockNLog — CEO Daily Risk Report", styles["Title"]))
    story.append(Spacer(1, 12))
    story.append(
        Paragraph(
            "<b>Overall risk score (portfolio):</b> {:.3f} &nbsp;|&nbsp; <b>Severity:</b> {}".format(
                float(kpi.get("score") or 0),
                kpi.get("severity") or "—",
            ),
            styles["Normal"],
        )
    )
    ch = kpi.get("change_percent")
    if ch is not None:
        story.append(Paragraph(f"<b>7d vs prior 7d change:</b> {ch:+.1f}%", styles["Normal"]))
    story.append(Spacer(1, 12))

    story.append(Paragraph("<b>Financial exposure (heuristic)</b>", styles["Heading2"]))
    story.append(
        Paragraph(
            "Estimated impact: <b>${:,.2f}</b>. {}".format(
                float(fin.get("estimated_impact") or 0),
                fin.get("estimated_impact_note") or "",
            ),
            styles["BodyText"],
        )
    )
    story.append(Spacer(1, 8))

    story.append(Paragraph("<b>Compliance</b>", styles["Heading2"]))
    story.append(
        Paragraph(
            "Status: <b>{}</b> (score {}). {}".format(
                comp.get("level") or "—",
                comp.get("score") if comp.get("score") is not None else "—",
                "; ".join(comp.get("reasons") or []),
            ),
            styles["BodyText"],
        )
    )
    story.append(Spacer(1, 8))

    story.append(Paragraph("<b>Key alerts</b>", styles["Heading2"]))
    if not alerts:
        story.append(Paragraph("No automated alerts for this snapshot.", styles["BodyText"]))
    for a in alerts[:12]:
        story.append(
            Paragraph(
                "<b>[{}]</b> {} — {}".format(
                    a.get("severity", "").upper(),
                    a.get("title", ""),
                    a.get("detail", ""),
                ),
                styles["BodyText"],
            )
        )
    story.append(Spacer(1, 8))

    story.append(Paragraph("<b>Top risky assets</b>", styles["Heading2"]))
    tbl_data = [["Asset", "Dept", "Avg risk", "Critical #", "Level"]]
    for row in assets[:15]:
        tbl_data.append(
            [
                str(row.get("asset_name") or row.get("asset_id") or ""),
                str(row.get("department") or "—"),
                f"{float(row.get('avg_risk_score') or 0):.3f}",
                str(row.get("critical_count") or 0),
                str(row.get("risk_level") or "—"),
            ]
        )
    t = Table(tbl_data, repeatRows=1)
    t.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a2332")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#0f1419"), colors.HexColor("#161d27")]),
            ]
        )
    )
    story.append(t)
    story.append(Spacer(1, 12))
    story.append(
        Paragraph(
            "<i>Generated by LockNLog. Heuristic scores; not legal or audit attestation.</i>",
            styles["Italic"],
        )
    )

    doc.build(story)
    return buf.getvalue()
